### ISSUE TITLE
missing a license

### ISSUE THREAD

**Issue by arthurvr** [ekremkaraca/awesome-rails#12]
This repo misses a license. You could use https://github.com/sindresorhus/awesome#license as inspiration.

**Comment by arthurvr** [comment]
closing as fixed in https://github.com/ekremkaraca/awesome-rails/commit/7de213dd906d83d3644e21e287ab2c219bcd7c85

**Comment by ekremkaraca** [comment]
Hi again,

I've added MIT license and thank you for your contribution!
