### ISSUE TITLE
Follow-all is not working.

### ISSUE THREAD

**Issue by sharprakeshverma** [ekremkaraca/awesome-rails#35]
In Readme.md file under social-networking, the "Follow-all" web app seems to be broken. We can remove the Live link from the readme.md after confirming I believe.

**Comment by ekremkaraca** [comment]
Hi @sharprakeshverma,

Thanks for your message but it seems the link you gave is working. Can you try visiting the link?

**Comment by sharprakeshverma** [comment]
Hey ekremkaraca,

Try login with Twitter on the first page. throws 500.

**Comment by ekremkaraca** [comment]
@sharprakeshverma The link was removed, thanks so much plus sorry for delay.
