### ISSUE TITLE
Looking for a maintainer

### ISSUE THREAD

**Issue by ekremkaraca** [ekremkaraca/awesome-rails#45]
Due to the army service, I'll be unable to access Internet for about 6-7 months. So, I'm looking for a maintainer for the list. If you want to be maintainer, let's discuss here.

**Comment by seanfcarroll** [comment]
Sure @ekremkaraca  I'll do it.

**Comment by ekremkaraca** [comment]
@seanfcarroll That's OK for me.

**Comment by seanfcarroll** [comment]
@ekremkaraca maybe you are too busy with the army, but perhaps you know someone for this: https://github.com/activerecord-hackery/ransack/issues/835

**Comment by ekremkaraca** [comment]
@seanfcarroll I'll discuss it with Turkish Rubyist friends.
