### ISSUE TITLE
A proposal for proprietary Rails projects 

### ISSUE THREAD

**Issue by ekremkaraca** [ekremkaraca/awesome-rails#7]
Hi guys,

Before beginning, I'd like to thank you all for your supports to this project. At first, I planned to list open-sourced Rails projects here but I'm unsure whether listing proprietary Rails projects here or not.

Here I've created a `PROPOSAL.md` file to preview and I've added here a project came from @asif31iqbal. What do you think, should we place proprietary Rails projects here?

**Comment by thiagoaugusto** [comment]
Hey man,

Congratulations for awesome-rails project. This initiative is very cool and important for our community.
